### ISSUE TITLE
Support Laravel 7.x

### ISSUE THREAD

**Issue by alistairreynolds** [ddzobov/laravel-pivot-softdeletes#3]

**Comment by kosmonowt** [comment]
please pull!

**Comment by alistairreynolds** [comment]
Have done here, although not done a pull request before, but pretty sure I've done it right?

https://github.com/ddzobov/laravel-pivot-softdeletes/pull/4

**Comment by ngunyimacharia** [comment]
Any progress with this?

**Comment by ddzobov** [comment]
Currently i’m working for PR to laravel with this. After code will be done i will publish it here

**Comment by ngunyimacharia** [comment]
Thank you @ddzobov . Will appreciate it

**Comment by mbryne** [comment]
Is this the PR you were referring too: https://github.com/laravel/framework/pull/31224

edit: can we accept the above #4 pull request in the interim?

**Comment by ngunyimacharia** [comment]
Seems the PR https://github.com/laravel/framework/pull/31224 is closed due to inactivity. I agree with @mbryne. Maybe review the pull request as we await the Laravel pull request to finish reviewing as it might take some time.

**Comment by ddzobov** [comment]
Released 2.0.0

**Comment by mbryne** [comment]
This is just a friendly prod on this issue https://github.com/laravel/framework/pull/31224 @ddzobov 

Love to see this great work in core
