### ISSUE TITLE
Softdeleting correct records in pivot table

### ISSUE THREAD

**Issue by canatufkansu** [ddzobov/laravel-pivot-softdeletes#5]
Hi,

First of all thanks for this great library, I have implemented following pivot table with your library but when I try to insert another record for the same user application soft deletes existing records for that user.

![image](https://user-images.githubusercontent.com/58461177/84386023-46211100-abf9-11ea-945c-60a806563505.png)

I'm using following code to associate a new record with the user

`Auth::user()->listings()->sync($newListing);`

System needs to soft delete if there is an existing record with same user_id and listing_id, but it seems that it is only checks the user_id to decide uniqueness. Am I missing anything ?

**Comment by ddzobov** [comment]
When you are using sync method you should provide new full list of records. Records not presented in list will be removed. If you want just add new record use attach method.

If my answer is not correct for you please provide full code sample with current DB values and new values.

**Comment by canatufkansu** [comment]
> When you are using sync method you should provide new full list of records. Records not presented in list will be removed. If you want just add new record use attach method.
> 
> If my answer is not correct for you please provide full code sample with current DB values and new values.

It worked! thank you.
